title: Giancarlos Ulloa
logo: /assets/Github_Profile.png
description: A data-driven professional with experience in operations analysis, real estate, and business ownership. I specialize in optimizing processes, analyzing market trends, and utilizing data insights to drive business growth and operational efficiency.

theme: jekyll-theme-minimal
